#!/bin/bash -l

# Set project
#$ -P textconv
#$ -o FULLTEST3.txt
#$ -m ea
#$ -j y
#$ -V
# Request 4 cpus

#$ -pe omp 4

# Request 2 gpus
#$ -l gpus=3

# Spec min gpu compute compatibility
#$ -l gpu_c=6


module load miniconda
conda activate py3

python3 train_vqvae.py -m '../models/full_test_models3' -r 'full_test3' -d "../data/all_midi_tensors_ttv" -s -u 2048
