#!/bin/bash -l

# Set project
#$ -P textconv
#$ -o vqvae_mae.txt
#$ -m ea
#$ -j y
#$ -V
#$ -l h_rt=24:00:00
# Request 4 cpus

#$ -pe omp 4

# Request 1 gpu
#$ -l gpus=1

# Spec min gpu compute compatibility
#$ -l gpu_c=6


module load miniconda
conda activate py3

python3 ../test_vqvae.py -l -r 'mae' 
