#!/bin/bash -l

# Set project
#$ -P textconv
#$ -o MSE_TEST_1.txt
#$ -m ea
#$ -j y
#$ -V
#$ -l h_rt=24:00:00
# Request 4 cpus

#$ -pe omp 4

# Request 1 gpu
#$ -l gpus=1

# Spec min gpu compute compatibility
#$ -l gpu_c=6


module load miniconda
conda activate py3

python3 train_vqvae.py -d /projectnb/textconv/sadiela/midi_generation/data/all_midi_tensors_ttv/train -m /models -o /results -r MSE_TEST_1 -s -v