#!/bin/bash -l

# Set project
#$ -P textconv
#$ -o sparsify_midis.txt
#$ -m ea
#$ -j y
#$ -V
# Request 4 cpus

#$ -pe omp 4

# Request 1 gpu
#$ -l gpus=1

# Spec min gpu compute compatibility
#$ -l gpu_c=6

module load miniconda
conda activate py3

python3 convert_to_sparse.py
