#!/bin/bash -l

# Set project
#$ -P textconv
#$ -o NEWREPVAE.txt
#$ -m ea
#$ -j y
#$ -V

# Request 4 cpus
#$ -pe omp 4

# Request 3 gpus
#$ -l gpus=3

# Spec min gpu compute compatibility
#$ -l gpu_c=6


module load miniconda
conda activate py3

python3 train_vqvae.py -m 'new_rep_vae' -r 'new_rep_vae' -s -q 
