#!/bin/bash -l

# Set project
#$ -P textconv
#$ -o vae_mse.txt
#$ -m ea
#$ -j y
#$ -V
#$ -l h_rt=24:00:00
# Request 4 cpus

#$ -pe omp 4

# Request 1 gpu
#$ -l gpus=2

# Spec min gpu compute compatibility
#$ -l gpu_c=6


module load miniconda
conda activate py3

python3 test_vqvae.py -r 'mse' -q